vlib work
vsim -voptargs="+acc" work.DSP_tb
add wave *
add wave -position end  sim:/DSP_tb/uut/A
add wave -position end  sim:/DSP_tb/uut/A0REG
add wave -position end  sim:/DSP_tb/uut/A1_ff
add wave -position end  sim:/DSP_tb/uut/A1REG
add wave -position end  sim:/DSP_tb/uut/A_ff
add wave -position end  sim:/DSP_tb/uut/B
add wave -position end  sim:/DSP_tb/uut/B0REG
add wave -position end  sim:/DSP_tb/uut/B1_ff
add wave -position end  sim:/DSP_tb/uut/B1REG
add wave -position end  sim:/DSP_tb/uut/B_ff
add wave -position end  sim:/DSP_tb/uut/B_INPUT
add wave -position end  sim:/DSP_tb/uut/BCIN
add wave -position end  sim:/DSP_tb/uut/BCOUT
add wave -position end  sim:/DSP_tb/uut/C
add wave -position end  sim:/DSP_tb/uut/C_ff
add wave -position end  sim:/DSP_tb/uut/carryin
add wave -position end  sim:/DSP_tb/uut/CARRYINREG
add wave -position end  sim:/DSP_tb/uut/CARRYINSEL
add wave -position end  sim:/DSP_tb/uut/carryout
add wave -position end  sim:/DSP_tb/uut/carryoutf
add wave -position end  sim:/DSP_tb/uut/CARRYOUTREG
add wave -position end  sim:/DSP_tb/uut/CEA
add wave -position end  sim:/DSP_tb/uut/CEB
add wave -position end  sim:/DSP_tb/uut/CEC
add wave -position end  sim:/DSP_tb/uut/CECARRYIN
add wave -position end  sim:/DSP_tb/uut/CED
add wave -position end  sim:/DSP_tb/uut/CEM
add wave -position end  sim:/DSP_tb/uut/CEOPMODE
add wave -position end  sim:/DSP_tb/uut/CEP
add wave -position end  sim:/DSP_tb/uut/clk
add wave -position end  sim:/DSP_tb/uut/CREG
add wave -position end  sim:/DSP_tb/uut/CYI
add wave -position end  sim:/DSP_tb/uut/CYO
add wave -position end  sim:/DSP_tb/uut/D
add wave -position end  sim:/DSP_tb/uut/D_A_B_concatenated
add wave -position end  sim:/DSP_tb/uut/D_ff
add wave -position end  sim:/DSP_tb/uut/DREG
add wave -position end  sim:/DSP_tb/uut/IS_BDIRECT
add wave -position end  sim:/DSP_tb/uut/IS_CARRYINSEL_CARRYIN
add wave -position end  sim:/DSP_tb/uut/IS_CARRYINSEL_OPMODE
add wave -position end  sim:/DSP_tb/uut/IS_SYNCRESET
add wave -position end  sim:/DSP_tb/uut/M
add wave -position end  sim:/DSP_tb/uut/M_ff
add wave -position end  sim:/DSP_tb/uut/MREG
add wave -position end  sim:/DSP_tb/uut/mult_out
add wave -position end  sim:/DSP_tb/uut/MUX1_out
add wave -position end  sim:/DSP_tb/uut/MUX_X_out
add wave -position end  sim:/DSP_tb/uut/MUX_Z_out
add wave -position end  sim:/DSP_tb/uut/opmode
add wave -position end  sim:/DSP_tb/uut/opmode_ff
add wave -position end  sim:/DSP_tb/uut/OPMODEREG
add wave -position end  sim:/DSP_tb/uut/P
add wave -position end  sim:/DSP_tb/uut/P_ff
add wave -position end  sim:/DSP_tb/uut/PCIN
add wave -position end  sim:/DSP_tb/uut/PCOUT
add wave -position end  sim:/DSP_tb/uut/post_addsub_cout
add wave -position end  sim:/DSP_tb/uut/post_addsub_out
add wave -position end  sim:/DSP_tb/uut/pre_addsub_cout
add wave -position end  sim:/DSP_tb/uut/pre_addsub_out
add wave -position end  sim:/DSP_tb/uut/PREG
add wave -position end  sim:/DSP_tb/uut/RSTA
add wave -position end  sim:/DSP_tb/uut/RSTB
add wave -position end  sim:/DSP_tb/uut/RSTC
add wave -position end  sim:/DSP_tb/uut/RSTCARRYIN
add wave -position end  sim:/DSP_tb/uut/RSTD
add wave -position end  sim:/DSP_tb/uut/RSTM
add wave -position end  sim:/DSP_tb/uut/RSTOPMODE
add wave -position end  sim:/DSP_tb/uut/RSTP
add wave -position end  sim:/DSP_tb/uut/RSTTYPE
add wave -position end  sim:/DSP_tb/uut/ZERO
run -all
#quit -sim
